# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os,sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from icons import resources



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(958, 719)
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 30, 491, 611))
        self.frame.setStyleSheet("border-image:url(:/background.jpg);\n"
"border-top-left-radius: 100px;\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(490, 30, 421, 611))
        self.label.setStyleSheet("background-color: rgba(255,255,255,255);\n"
"border-bottom-right-radius: 100px\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.kullanici_girisi = QtWidgets.QLabel(Form)
        self.kullanici_girisi.setGeometry(QtCore.QRect(570, 68, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.kullanici_girisi.setFont(font)
        self.kullanici_girisi.setStyleSheet("color: rgba(1, 34, 87);")
        self.kullanici_girisi.setObjectName("kullanici_girisi")
        self.kullanici_adi = QtWidgets.QLineEdit(Form)
        self.kullanici_adi.setGeometry(QtCore.QRect(570, 328, 221, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kullanici_adi.setFont(font)
        self.kullanici_adi.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(230, 105, 14); /* Turuncu çizgi */\n"
"    color: rgb(1, 34, 87); /* Logo lacivertine uyumlu yazı rengi */\n"
"    padding-bottom: 7px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.kullanici_adi.setInputMethodHints(QtCore.Qt.ImhNone)
        self.kullanici_adi.setObjectName("kullanici_adi")
        self.parola = QtWidgets.QLineEdit(Form)
        self.parola.setGeometry(QtCore.QRect(570, 388, 221, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.parola.setFont(font)
        self.parola.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    border-bottom: 2px solid rgb(230, 105, 14); /* Turuncu çizgi */\n"
"    color: rgb(1, 34, 87); /* Logo lacivertine uyumlu yazı rengi */\n"
"    padding-bottom: 7px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.parola.setEchoMode(QtWidgets.QLineEdit.Password)
        self.parola.setObjectName("parola")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(570, 460, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, x1:0, y1:0.5, x2:1, y2:0.5,\n"
"        stop:0 rgba(1, 34, 87, 230),       /* Logo Mavisi */\n"
"        stop:1 rgba(230, 105, 14, 230)     /* Logo Turuncusu */\n"
"    );\n"
"    color: rgba(255, 255, 255, 230);       /* Beyaz yazı */\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        spread:pad, x1:0, y1:0.5, x2:1, y2:0.5,\n"
"        stop:0 rgba(1, 30, 70, 255),        /* Daha koyu mavi tonu */\n"
"        stop:1 rgba(255, 130, 30, 255)      /* Parlak turuncu tonu */\n"
"    );\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: rgba(1, 25, 60, 255); /* Koyu mavi */\n"
"}\n"
"\n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5 {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color: rgba(1, 34, 87, 255); /* Logo Mavisi */\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover {\n"
"    color: rgba(230, 105, 14, 255); /* Logo Turuncusu */\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    color: rgba(180, 85, 10, 255); /* Daha koyu turuncu */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.kullanici_girisi.setText(_translate("Form", "Kullanıcı Girişi"))
        self.kullanici_adi.setPlaceholderText(_translate("Form", "Kullanıcı Adı"))
        self.parola.setPlaceholderText(_translate("Form", "Parola"))
        self.pushButton.setText(_translate("Form", "G i r i ş"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
